# Generated by Django 3.2.9 on 2021-11-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='is_completed',
            field=models.IntegerField(choices=[(1, 'Completed'), (0, 'Not completed')], default=0),
        ),
    ]
